handle new cygwin directory structure

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -386,7 +386,10 @@ case "$osname" in
     if test ! -d $cygtop; then
       cygtop=/Cygnus/cygwin-B$ver
       if test ! -d $cygtop; then
-        echo ..."I could not find Cygwin top directory" >&2
+        cygtop=/usr/${arch}-pc-cygwin
+        if test ! -d $cygtop; then
+          echo ..."I could not find Cygwin top directory" >&2
+        fi
       fi
     fi;;
 esac
@@ -395,6 +398,7 @@ if test "$optimization" != profiling; then
 # First, construct the PATHs
  case "$osname" in
    cygwin*) libpth="
+        $cygtop/lib\
  	$cygtop/H-${arch}-cygwin32/lib\
  	$cygtop/H-${arch}-cygwin32/${arch}-cygwin32/lib\
      ";;
