test that CC is working before going on

diff --git a/config/get_cc b/config/get_cc
--- a/config/get_cc
+++ b/config/get_cc
@@ -72,6 +72,16 @@ EOT
   CC=$ans
 fi
 
+exe=$osname-$arch-gnu$$
+if ($CC $CFLAGS gnu.c 2>/dev/null); then :
+else
+  echo "***************************************************************"
+  echo "*  C compiler is not functional. Aborting.                    *"
+  echo "***************************************************************"
+  exit 1;
+fi
+rm -f $exe $exe$exe_suff
+
 if test "$CC" != "$gcc"; then __gnuc__=; fi
 if test -z "$__gnuc__"; then
   exe=$osname-$arch-gnu$$
@@ -80,7 +90,7 @@ if test -z "$__gnuc__"; then
     __gnuc__=`$CC -v 2>&1 | sed -n 's/.*version //p'`
     echo GNU compiler version $__gnuc__
   fi
-  rm -f $exe
+  rm -f $exe $exe$exe_suff
 fi
 
 # Which Flags for Compiler ?
